# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'rn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rn
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    'RCTActionSheet',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTSettings',
    'RCTVibration',
    'RCTPushNotification',
    'RCTCameraRoll',
    'RCTBlob',
    'RCTGeolocation', 
    ]
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'


  pod 'RNLanguages', :path => '../node_modules/react-native-languages'

  pod 'ReactNativeNavigation', :path => '../node_modules/react-native-navigation'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNKeychain', :path => '../node_modules/react-native-keychain'


  pod 'react-native-blur', :path => '../node_modules/@react-native-community/blur'


  pod 'TouchID', :path => '../node_modules/react-native-touch-id'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'

  pod 'ViroKit_static_lib', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/static_lib'
end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings['ENABLE_BITCODE'] = 'YES'
#     end
#   end
# end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    # target.build_configurations.each do |config|
    #   config.build_settings['ENABLE_BITCODE'] = 'YES'
    # end
    if target.name == "React"
      target.remove_from_project
    end
  end

  system(". ./podFix.sh")
end
